Fatiando Arrays

In [7]:
import numpy as np

In [8]:
array = np.array([[1,2,3,4,5],
                 [6,7,8,9,10],
                 [11,12,13,14,15],
                 [16,17,18,19,20]])

array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
# Fatiando as duas primeiras linhas

fatiando = array[0:2, :]
fatiando

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
# Fatiando as três primeiras colunas

fatiando2 = array[: , 0:3]
fatiando2

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])