Ess tipo de arquivo trabalha não com linhas mas com células

a[linhas, colunas]



In [6]:
import numpy as np


a = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

# Número de dimensões (eixos) do array.
print(a.ndim)

#

2


In [ ]:
#Shape/Formato - Uma tupla que indica o tamanho do array em cada dimensão. No 
# caso do exemplo são 3 linhas com 3 colunas

print(a.shape)


(3, 3)


In [12]:
#Buscar elemento na linha 1  e coluna 2

print( a[0,1])

2


Pegando a coluna ou a linha 

Código	   O que retorna

a[0, :]	   primeira linha
a[:, 0]	   primeira coluna
a[1, :]	   segunda linha
a[:, 2]	   terceira coluna

In [16]:
# Pegando a coluna 1 
print(a[:, 0])

# Pegando a linha 1 

print(a[0, :])

[1 4 7]
[1 2 3]


Fatiando Arrays

In [18]:
# Fatiando para criar subarrays 

sub = a[0:2, 1:3]
sub

# No caso eu queria da linha 0 a linha 1 e da coluna 1 até a 2, assim o 
# último número sempre é o próximo que queremos. 

array([[2, 3],
       [5, 6]])