In [3]:
import numpy as np

In [9]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [10]:
# Adição

soma = np.add(array,10)
soma

array([11, 12, 13, 14, 15])

In [11]:
# Subtração

sub = np.subtract(array,1)
sub

array([0, 1, 2, 3, 4])

In [13]:
# Multiplicação

multi = np.multiply(array,2)
multi

array([ 2,  4,  6,  8, 10])

In [14]:
#Divisão 

div = np.divide(array, 2)
div

array([0.5, 1. , 1.5, 2. , 2.5])

In [19]:
#Potência

potencia = np.pow(array, 2)
potencia

array([ 1,  4,  9, 16, 25])

Funções estatísticas

In [15]:
#Média

media = np.mean(array)
media

np.float64(3.0)

In [16]:
#Desvio Padrão

dev_padrao = np.std(array)
dev_padrao

np.float64(1.4142135623730951)

In [17]:
#Comparação de valores do Array

maior_que_2 = array > 2 
maior_que_2

array([False, False,  True,  True,  True])

In [18]:
# Combinando Funções

resposta = np.sqrt(array) + np.mean(array)
resposta

array([4.        , 4.41421356, 4.73205081, 5.        , 5.23606798])