Copy - cria uma nova cópia na memória, assim criamos elementos independentes (original e cópia)

View - contrário do copy, ela compartilha os mesmos dados do elemento original

In [3]:
import numpy as np

In [4]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# View (Podemos considerar que o fatiamento é um tipo de view)

array_view = array[1:,1:]
array_view

array([[5, 6],
       [8, 9]])

In [ ]:
# Para modificar o array view atribui que a 1 linha na 1 coluna, sendo que 
# acabamos por modificar nosso array original. 

array_view[0,0] = 99 
print(array_view)
print(array)

[[99  6]
 [ 8  9]]
[[ 1  2  3]
 [ 4 99  6]
 [ 7  8  9]]


Para preservar o array original temos que usar copy

In [ ]:
array_copia = array.copy()